### ISSUE TITLE
list of common deps to include...

### ISSUE THREAD

**Issue by sirvon** [saadfarooq/gradle-common-deps-plugin#1]
Thanks for your work!

Which dependencies can be used in this setup, so far?

**Comment by saadfarooq** [comment]
The ones on the Readme... I'll make sure to point that out there and also add a guide for people to add more.

**Comment by saadfarooq** [comment]
I added more details including the dependencies list and contribution guidelines to the README.This should resolve this issue. Please reopen if necessary.
